// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDV9uCz-eyG5aZNy9pRaVQ-5GMqV4wjPj8',
    appId: '1:173663391916:android:1deeba12c7aaf0973c4f09',
    messagingSenderId: '173663391916',
    projectId: 'flutter-ci-demo-9a576',
    storageBucket: 'flutter-ci-demo-9a576.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0P1LmwYKOKfl9dQyZdL96EHpeYdXVLAQ',
    appId: '1:173663391916:ios:7a2d51411cf740a03c4f09',
    messagingSenderId: '173663391916',
    projectId: 'flutter-ci-demo-9a576',
    storageBucket: 'flutter-ci-demo-9a576.appspot.com',
    iosClientId: '173663391916-6dirhgrg6a2dn87dpjdp4eneq3aatt5m.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterTestDemo',
  );
}
