name: Continuous Integration

on:
  pull_request:
    branches:
      - main


jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Report code coverage
        uses: zgosalvez/github-actions-report-lcov@v1
        with:
          coverage-files: coverage/lcov.*.info
          minimum-coverage: 90
          artifact-name: code-coverage-report
          # github-token: ${{ secrets.GITHUB_TOKEN }}
          working-directory: ./
